apiVersion: v1
kind: Namespace
metadata:
  name: excalidraw
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: excalidraw
  namespace: excalidraw
  labels:
    app: excalidraw
spec:
  replicas: 2
  selector:
    matchLabels:
      app: excalidraw
  template:
    metadata:
      labels:
        app: excalidraw
    spec:
      containers:
        - name: excalidraw
          image: excalidraw/excalidraw:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: excalidraw
  namespace: excalidraw
  labels:
    app: excalidraw
spec:
  type: ClusterIP
  selector:
    app: excalidraw
  ports:
    - name: http
      port: 80
      targetPort: http
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: excalidraw-tls
  namespace: excalidraw
spec:
  secretName: excalidraw-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  dnsNames:
    - excalidraw.saas.example.com
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: excalidraw-gateway
  namespace: excalidraw
spec:
  gatewayClassName: traefik
  listeners:
#     - name: web
#       protocol: HTTP
#       port: 8000
#       hostname: excalidraw.saas.example.com
#       allowedRoutes:
#         namespaces:
#           from: Same
    - name: websecure
      protocol: HTTPS
      port: 8443
      hostname: excalidraw.saas.example.com
      allowedRoutes:
        namespaces:
          from: Same
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: excalidraw-tls
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: excalidraw-route
  namespace: excalidraw
spec:
  parentRefs:
    - name: excalidraw-gateway
  hostnames:
    - excalidraw.saas.example.com
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: excalidraw
          port: 80
