apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  # name: nextcloud-tls
  name: nextcloud.saas.example.com-tls
  namespace: nextcloud
spec:
  secretName: nextcloud.saas.example.com-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  dnsNames:
    - nextcloud.saas.example.com
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: nextcloud-saas-gateway
  namespace: nextcloud
spec:
  gatewayClassName: traefik
  listeners:
    # - name: web
    #   protocol: HTTP
    #   port: 8000
    #   hostname: nextcloud.saas.example.com
    #   allowedRoutes:
    #     namespaces:
    #       from: Same
    - name: websecure
      protocol: HTTPS
      port: 8443
      hostname: nextcloud.saas.example.com
      allowedRoutes:
        namespaces:
          from: Same
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: nextcloud.saas.example.com-tls
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: nextcloud-route
  namespace: nextcloud
spec:
  parentRefs:
    - name: nextcloud-saas-gateway
  hostnames:
    - nextcloud.saas.example.com
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: nextcloud
          port: 8080
